// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entity "coffee-online-cli/entity"

	mock "github.com/stretchr/testify/mock"
)

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: order
func (_m *Writer) CreateOrder(order *entity.Order) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderPayment provides a mock function with given fields: order
func (_m *Writer) OrderPayment(order *entity.Order) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for OrderPayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOrderShippingStatus provides a mock function with given fields: orderID, shippingStatus
func (_m *Writer) UpdateOrderShippingStatus(orderID int, shippingStatus entity.ShippingStatus) error {
	ret := _m.Called(orderID, shippingStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderShippingStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, entity.ShippingStatus) error); ok {
		r0 = rf(orderID, shippingStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWriter creates a new instance of Writer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Writer {
	mock := &Writer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
