// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entity "coffee-online-cli/entity"

	mock "github.com/stretchr/testify/mock"
)

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: product
func (_m *Writer) CreateProduct(product entity.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductStockUpdate provides a mock function with given fields: id, newStock
func (_m *Writer) ProductStockUpdate(id int, newStock int) error {
	ret := _m.Called(id, newStock)

	if len(ret) == 0 {
		panic("no return value specified for ProductStockUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(id, newStock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWriter creates a new instance of Writer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Writer {
	mock := &Writer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
